services:
  cowrie:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  web-honeypot:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  dionaea:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /opt/dionaea/var/dionaea/roots/ftp
      - /opt/dionaea/var/dionaea/roots/www
      - /opt/dionaea/var/dionaea/roots/upnp
      - /opt/dionaea/var/dionaea/bistreams
      - /opt/dionaea/var/dionaea/binaries
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  pipeline:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  redis:
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  mysql:
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

  elasticsearch:
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2048M

  logstash:
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

  filebeat:
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
